baseURL: "https://gmishra.in"
canonifyURLs: true
relativeURLs: false 
title: Gaurav Mishra
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Experience
          url: experience/
          weight: 1
        - name: Research
          url: research/
          weight: 2
        - name: Projects
          url: projects/
          weight: 3
        - name: Education
          url: education/
          weight: 4
        - name: Music & Life
          url: personal/
          weight: 5
        - name: Contact
          url: contact/
          weight: 6

params:
    description: "This website hosts Gaurav Mishra's research, projects, experience, and contact information."
    author: Gaurav Mishra
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["experience","research","projects","education","personal"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: false
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Gaurav Mishra
          subtitle: "Senior Machine Learning Scientist at Merck specializing in machine learning, computer vision, and NLP with 6+ years of experience bridging AI research and industry applications. Based in Philadelphia, PA, with interests in Hindustani classical music, outdoor activities, boardgame, plants and cats."
          imageUrl: "picture.jpeg"
          imageWidth: 200
          imageHeight: 200
          buttons:
            - name: Experience
              url: experience/
            - name: Education
              url: education/
            - name: Research
              url: research/
            - name: Projects
              url: projects/
            - name: Music & Life
              url: personal/
            - name: Resume
              url: cv.pdf

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:in.gaurav.mishra@gmail.com
        - name: LinkedIn
          url: https://linkedin.com/in/ingauravmishra
        - name: GitHub
          url: https://github.com/mishragauravgm
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=gdi0oOMAAAAJ

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Gaurav Mishra"
      icon: cat-favicon.png
      iconHeight: 25

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2